### ISSUE TITLE
Bleak 0 devices found on Windows 10

### ISSUE THREAD

**Issue by fcondo** [hbldh/bleak#353]
* bleak version: 0.9.1
* Python version: 3.7.4rc1
* Operating System: Windows 10 Pro version 2004
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description
I want to read gyroscope and acceleration values from an Arduino Nano 33 BLE board by using Bleak on a Windows OS. The code to make the discovery is the default Bleak code. On Arduino I use the BatteryLevel example of Arduino Tutorial on their IDE, which is similar to this [one](https://rootsaid.com/arduino-ble-example/).

### What I Did
I enabled bleak debug mode, with the following result:
```
2020-10-30 08:04:08,333 bleak.backends.dotnet.discovery DEBUG: 0 devices found. Watcher status: 4.
```
Using the Android nRF Connect application I can view the device and the characteristic. Using Bleak instead I can't see any device. A few days ago, without modifications, I was able to discover, in a discontinuous way, some BLE devices. Now I can't find any of them anymore, without changing anything. 

Is it possible to have a problem with permissions on Windows? I tried to connect it via Bluetooth to the pc first, but Windows 10 says: try to connect your device again. But the Arduino sketch sees the connection attempt as a Central BLE device connecting, in fact, it enters the while loop of the Arduino code and starts sending data. How to solve it?

EDIT: restarting the Bluetooth service lead me to a working BLE scan. I think the problem is using Ctrl+C to kill the process.

**Comment by hbldh** [comment]
This is either another instance of this issue https://github.com/hbldh/bleak/issues/257 or due to your Ctrl-C handling.

Watcher status 4 means _"An error occurred during transition or scanning that stopped the watcher due to an error."_ (https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcherstatus?view=winrt-19041) So probably the BLE Scanner got stuck in scanning mode or something similar.

I do not think Bleak can be improved to handle this in a good fashion. Will close this.
