### ISSUE TITLE
write_gatt_char(..., response=True) not returning bytearray

### ISSUE THREAD

**Issue by skjerns** [hbldh/bleak#59]
* bleak version: 0.4.0 
* Python version: 3.7
* Operating System: win 10

As mentioned in issue #58 I have problems receiving an answer from a characteristic that has no read attribute. I'm performing a write and would expect response `~WORLD`. This works fine in Bluetooth LE Explorer.

However, I can't seem to get this working in bleak
```Python
answer = await client.write_gatt_char(rw_charac, b'~HELLO', response=True)
# no response is given, answer is always None
```

according to the documentation, the `write_gatt_char(..., response=True)` should return
` if not response=True, a bytearray is returned.`, but this does not seem to happen? Any tips how I can receive an answer? Should I use any other method instead?

**Comment by hbldh** [comment]
The `write` and `write-with-response` is case where the .NET and Linux backends differ right now, and it is the Windows version that is more correct. It will be remedied soon. 

The documentation is wrong, the Windows method does not return anything, mostly due to the fact that the actual response obtained does not contain anything worthy of returning (https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattwriteresult).
In the Linux backend, I perform a `read_gatt_char` after the `write_gatt_char` and this is the bytearray returned, but this is (as shown in your case) not always possible. It will be changed, since I have realized that I also missed sending the `write-with-response` correctly there... (https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n89)

The response idea of BLE is not the same as response from a function in programming, but more of an acknowledgement from the server that it has written the value and an error in case it hasn't.

Try adding a notification before writing and see if the "response" you see in Bluetooth LE Explorer comes from that:

```python
await client.start_notify(rw_charac, notification_handler)
await client.write_gatt_char(rw_charac, b'~HELLO', response=True)
await asyncio.sleep(0.5, loop=loop)  # Sleeping just to make sure the response is not missed...
await client.stop_notify(rw_charac)
```
