### ISSUE TITLE
Why is GitHub action build_and_test only run for branches develop and master?

### ISSUE THREAD

**Issue by jackjansen** [hbldh/bleak#905]
Subject says all: is there a reason not to run the build action on other branches?

Right now my first commit on a branch is always to enable the CI/CD for the branch, and the last commit is disabling it again.

**Comment by dlech** [comment]
For branches in this repo, it would cause CI to run twice for pull requests, once for the branch and once for the pull request.

So I guess if you want to run CI in your own repo instead of creating a PR here, you could create a PR in your own repo and it would have the same effect of running CI without requiring the extra commits.
